name: hao4k

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  Hao4K-autoSignIn:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Set python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: python -m pip install --upgrade requests
    
    - name: Hao4k auto sign in
      env:
        HAO4K_USERNAME: ${{ secrets.6868521 }}
        HAO4K_PASSWORD: ${{ secrets.LCY2002LCY }}
        SERVERCHAN_SCKEY: ${{ secrets.SCU157678T78f1ca4e7c8e21e067ac13cb6c41c6ca601a09a6d3deb }}
      run: python signin.py
